# Generated by Django 4.2.16 on 2025-01-23 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("AplikasiKasirWarmindo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barang",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
